#!/bin/bash
# Run full guideseq pipeline

# Copy script and config files as they were run
TIMESTAMP=$(date +%Y%m%d_%H%M%S)
SCRIPT=$0
SCRIPT_NAME=$(basename "$SCRIPT")
CONFIG_FILE=$1
CONFIG_FILENAME=$(basename "$CONFIG_FILE")
LOG_FOLDER="99_logfiles"
RESULT_FOLDER="12_results"

# Log all output
exec > >(tee "$LOG_FOLDER"/"$TIMESTAMP"_guideseq_ibis_run.log) 2>&1

print_logo () {
    echo ""
    echo "GUIDE-seq IBIS pipeline"
}

print_logo

# Import configfile and keep copy in 00_archive/log_files
if [ -e "$CONFIG_FILE" -a -s "$CONFIG_FILE" ]
then
    source "$CONFIG_FILE"
    cp "$CONFIG_FILE" "$LOG_FOLDER"/"$TIMESTAMP"_"$CONFIG_FILENAME"
    #cp "$INFO_FILE" "$LOG_FOLDER"/"$TIMESTAMP"_$(basename "$INFO_FILE")

else
    echo -e "\nGUIDE-seq IBIS: Config file does not exist or is empty."
    echo -e "        Please specify a valid config file."
    exit 1
fi

# Validate that database and samples are present
if ! ./01_scripts/00_validate_project.sh
then
    exit 1
fi

# Trim and clean reads
echo -e "\nGUIDE-seq IBIS: Trimming and filtering reads\n"
./01_scripts/01_trim.sh "$NCPUS" "$MIN_LENGTH" "$CROP_LENGTH"

# Extract reads, filter and annotate
echo -e "\nGUIDE-seq IBIS: Extracting, filtering, and annotating reads\n"
./01_scripts/02_extract.sh "$NCPUS" "$MIN_LENGTH"

# Map fasta reads to genome
echo -e "\nGUIDE-seq IBIS: Mapping fasta reads to genome\n"
./01_scripts/03_map.sh "$NCPUS" "$GENOME_FILE"

# Remove PCR duplicates
echo -e "\nGUIDE-seq IBIS: Removing PCR duplicates\n"
./01_scripts/04_deduplicate.sh "$NCPUS"

# Find Double Stranded Breaks (DSBs)
echo -e "\nGUIDE-seq IBIS: Find Double Stranded Breaks (DSBs)\n"
./01_scripts/05_dsb.sh "$NCPUS" "$MIN_LENGTH"

# Summarize results
echo -e "\nGUIDE-seq IBIS: Create report\n"
cat 09_sites/* | head -1 > guideseq_ibis_report.tsv
for i in 09_sites/*.dsb
do
    grep -v "^Sample" "$i"
done >> guideseq_ibis_report.tsv

# Report number of reads per step
# NOTE: For debugging purposes, otherwise keep commented out
#echo -e "\nGUIDE-seq IBIS: Report number of reads per step\n"
#./01_scripts/util/report_num_reads_per_step.sh
