#!/bin/bash
# Run full guideseq pipeline

# Copy script and config files as they were run
TIMESTAMP=$(date +%Y%m%d_%H%M%S)
SCRIPT=$0
SCRIPT_NAME=$(basename "$SCRIPT")
CONFIG_FILE=$1
CONFIG_FILENAME=$(basename "$CONFIG_FILE")
LOG_FOLDER="99_logfiles"
RESULT_FOLDER="12_results"

# Log all output
exec > >(tee "$LOG_FOLDER"/"$TIMESTAMP"_guideseq_ibis_run.log) 2>&1

print_logo () {
    echo ""
    echo "GUIDEseq IBIS pipeline"
}

print_logo

# Import configfile and keep copy in 00_archive/log_files
if [ -e "$CONFIG_FILE" -a -s "$CONFIG_FILE" ]
then
    source "$CONFIG_FILE"
    cp "$CONFIG_FILE" "$LOG_FOLDER"/"$TIMESTAMP"_"$CONFIG_FILENAME"
    #cp "$INFO_FILE" "$LOG_FOLDER"/"$TIMESTAMP"_$(basename "$INFO_FILE")

else
    echo -e "\nGUIDEseq IBIS: Config file does not exist or is empty."
    echo -e "        Please specify a valid config file."
    exit 1
fi

# Validate that database and samples are present
if ! ./01_scripts/00_validate_project.sh
then
    exit 1
fi

# Trim and clean reads
echo -e "\nBARQUE: Trimming and filtering reads"
./01_scripts/01_trim.sh "$NCPUS" "$MIN_LENGTH" "$CROP_LENGTH"
